fix(resources): crash on datetime.replace
`datetime.replace()` function doesn't manage days from us.

As consequence `(2017, 10, 31).replace(month=11)` will try to create
the date `(2017, 11, 31)` which doesn't exist.

In such case datetime lib crash with the following error:
```
ValueError: day is out of range for month
```

This commit replace the use of `datetime.replace()` to increment months
and years, by the use of `datetime + relativedelta()`.

`relativedelta()` function is part of `python-dateutil`, so I also add
the dependency in `setup.py`.