CI: Restore previous pip install method
This reverts commit 1ad01ad "CI: Install python3-build & add
--break-system-packages for Localstripe", merged 5 days ago.

Since then, the CI broke again, with errors like:

    $ python -m build
    RuntimeError: Virtual environment creation failed, executable
    /tmp/build-…/local/bin/python missing

I found that using our previous `pip install` commands worked. GitHub or
Ubuntu maintainers probably fixed the inconveniences described by Hoël
at https://github.com/adrienverge/localstripe/pull/234.