chore(CI): Disable flake8 for Python nightly
Because it currently fails with errors:

    AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'